import os
OPENAI_API_KEY = os.environ.get("OPENAI_API_KEY", "")
MISTRAL_API_KEY = os.environ.get("MISTRAL_API_KEY", "")
KNOWLEDGE_EXTRACTION_MODEL = "gpt-4.1"
RELEVANCE_CHECK_MODEL = "gpt-5-mini"
SECTION_SUMMARIZATION_MODEL = "gpt-4.1"
TOC_EXTRACTION_MODEL = "gpt-4o"
SUBTOPIC_SELECTION_MODEL = "gpt-5-chat-latest"
SUBTOPIC_RELEVANT_TEXT_EXTRACTION_MODEL = "gpt-4.1"
QUERY_EXPANSION_MODEL = "gpt-5-chat-latest"